const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORAGE='mileageTrackerTestDriveV1';
const defaults={settings:{driver:'',vanReg:'VN22 XBC',homeLocation:'',workLocation:'Stage Electrics, Bristol',currentOdo:48236,monthStartOdo:null,monthEndOdo:null},journeys:[],active:null};
let state=JSON.parse(localStorage.getItem(STORAGE)||'null')||structuredClone(defaults);
state.settings={...defaults.settings,...(state.settings||{})}; state.journeys=state.journeys||[];
let selectedType='Work',missedType='Work',watchId=null,timerId=null,deferredInstallPrompt=null;
const fmt=n=>(Number(n)||0).toLocaleString(undefined,{minimumFractionDigits:1,maximumFractionDigits:1});
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));renderAll()}
function currentMonthKey(d=new Date()){return d.toISOString().slice(0,7)}
function monthJourneys(){return state.journeys.filter(j=>String(j.date).slice(0,7)===currentMonthKey())}
function totals(){let w=0,p=0;monthJourneys().forEach(j=>j.type==='Work'?w+=+j.miles:p+=+j.miles);return{w,p,t:w+p}}
function showScreen(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));window.scrollTo(0,0);if(id==='active')startTimer()}
function renderAll(){const t=totals();$('#vanRegHome').textContent=state.settings.vanReg||'—';$('#driverHome').textContent=state.settings.driver||'Driver';$('#odoHome').textContent=Number(state.settings.currentOdo||0).toLocaleString();$('#workTotal').textContent=fmt(t.w);$('#personalTotal').textContent=fmt(t.p);$('#allTotal').textContent=fmt(t.t);$('#monthWork').textContent=fmt(t.w);$('#monthPersonal').textContent=fmt(t.p);$('#monthTotal').textContent=fmt(t.t);$('#monthLabel').textContent=new Date().toLocaleDateString(undefined,{month:'long',year:'numeric'});$('#activeResume').classList.toggle('hidden',!state.active);renderHistory();renderMonthly();if(state.active)renderActive()}
function renderHistory(){const root=$('#historyList'),js=[...state.journeys].sort((a,b)=>new Date(b.date)-new Date(a.date));if(!js.length){root.innerHTML='<div class="center subtle">No journeys recorded yet.</div>';return}root.innerHTML=js.map(j=>`<div class="journey"><div class="row space"><div><div class="journey-title">${esc(j.from)} → ${esc(j.to)}</div><div class="journey-meta">${new Date(j.date).toLocaleString()} · <span class="tag ${j.type.toLowerCase()}">${j.type.toUpperCase()}</span>${j.purpose?' · '+esc(j.purpose):''}</div></div><div class="miles">${(+j.miles).toFixed(1)} mi</div></div></div>`).join('')}
function renderMonthly(){const js=monthJourneys(),starts=js.map(j=>+j.startOdo).filter(Number.isFinite),ends=js.map(j=>+j.endOdo).filter(Number.isFinite);const s=state.settings.monthStartOdo??(starts.length?Math.min(...starts):null),e=state.settings.monthEndOdo??(ends.length?Math.max(...ends):null);$('#monthStartOdo').textContent=s==null?'—':Number(s).toLocaleString();$('#monthEndOdo').textContent=e==null?'—':Number(e).toLocaleString();const box=$('#reconcileBox'),t=totals();if(s!=null&&e!=null){const travelled=e-s,diff=travelled-t.t;box.className='notice top-gap '+(Math.abs(diff)<0.11?'ok':'warn');box.textContent=`Van travelled ${fmt(travelled)} miles · Recorded ${fmt(t.t)} miles · Difference ${fmt(diff)} miles${Math.abs(diff)<0.11?' ✓':''}`}else{box.className='notice top-gap';box.textContent='Enter monthly start/end odometer in Settings to reconcile mileage.'}}
function hav(a,b){const R=3958.7613,rad=x=>x*Math.PI/180,dLat=rad(b.lat-a.lat),dLon=rad(b.lng-a.lng),q=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function locate(cb){if(!navigator.geolocation)return alert('Geolocation is not supported by this browser.');navigator.geolocation.getCurrentPosition(p=>cb({lat:p.coords.latitude,lng:p.coords.longitude}),()=>alert('Location access was not available. You can still enter the start manually.'),{enableHighAccuracy:true,timeout:10000})}
function renderActive(){const a=state.active;if(!a)return;$('#activeFrom').textContent=a.from;$('#activeTo').textContent=a.to;$('#activeType').textContent=a.type.toUpperCase();$('#activeType').className='tag '+a.type.toLowerCase();$('#liveMiles').textContent=(a.miles||0).toFixed(2)}
function startTimer(){clearInterval(timerId);timerId=setInterval(()=>{if(!state.active)return;const sec=Math.max(0,Math.floor((Date.now()-state.active.startedAt)/1000)),m=String(Math.floor(sec/60)).padStart(2,'0'),s=String(sec%60).padStart(2,'0');$('#timer').textContent=`${m}:${s}`},1000)}
function startGps(){if(!navigator.geolocation||!state.active||watchId!=null)return;watchId=navigator.geolocation.watchPosition(p=>{const pt={lat:p.coords.latitude,lng:p.coords.longitude},a=state.active;if(!a)return;if(a.lastPoint){const d=hav(a.lastPoint,pt);if(d<1)a.miles=(a.miles||0)+d}a.lastPoint=pt;a.points=(a.points||0)+1;localStorage.setItem(STORAGE,JSON.stringify(state));renderActive()},()=>{}, {enableHighAccuracy:true,maximumAge:3000,timeout:10000})}
function stopGps(){if(watchId!=null&&navigator.geolocation)navigator.geolocation.clearWatch(watchId);watchId=null}
function setDestination(value){if(!value)return alert('Set this location first in Settings.');$('#destInput').value=value}
function setStart(value){if(!value)return alert('Set this location first in Settings.');$('#fromInput').value=value}
function companyRows(){return monthJourneys().filter(j=>j.type==='Work').sort((a,b)=>new Date(a.date)-new Date(b.date))}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

$$('nav button').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));
$('#newJourneyBtn').onclick=()=>{selectedType='Work';$$('.choice').forEach(b=>b.classList.toggle('selected',b.dataset.type==='Work'));$('#purposeField').classList.remove('hidden');$('#fromInput').value='Current location';$('#destInput').value='';$('#purposeInput').value='';$('#startOdoInput').value=state.settings.currentOdo||'';showScreen('new')};
$('#cancelNewBtn').onclick=()=>showScreen('home');
$$('.choice').forEach(b=>b.onclick=()=>{selectedType=b.dataset.type;$$('.choice').forEach(x=>x.classList.toggle('selected',x===b));$('#purposeField').classList.toggle('hidden',selectedType==='Personal')});
$('#useLocationBtn').onclick=()=>locate(pt=>{$('#fromInput').value=`Current location (${pt.lat.toFixed(5)}, ${pt.lng.toFixed(5)})`});
$('#fromHomeBtn').onclick=()=>setStart(state.settings.homeLocation); $('#toHomeBtn').onclick=()=>setDestination(state.settings.homeLocation); $('#toWorkBtn').onclick=()=>setDestination(state.settings.workLocation);
$('#startBtn').onclick=()=>{const from=$('#fromInput').value.trim(),to=$('#destInput').value.trim();if(!from||!to)return alert('Please enter a start and destination.');state.active={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),from,to,type:selectedType,purpose:$('#purposeInput').value.trim(),startedAt:Date.now(),startDate:new Date().toISOString(),startOdo:$('#startOdoInput').value===''?null:parseFloat($('#startOdoInput').value),miles:0,lastPoint:null,points:0};save();showScreen('active');startGps();setTimeout(()=>$('#openMapsBtn').click(),250)};
$('#openMapsBtn').onclick=()=>{if(!state.active)return;window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(state.active.to)}`,'_blank')};
$('#finishBtn').onclick=()=>{if(!state.active)return;stopGps();$('#finishMilesInput').value=(state.active.miles||0).toFixed(2);$('#finishOdoInput').value=state.active.startOdo!=null?(state.active.startOdo+(state.active.miles||0)).toFixed(1):'';$('#finishSummary').innerHTML=`<strong>${esc(state.active.from)} → ${esc(state.active.to)}</strong><div class="small top-gap">${state.active.type} · GPS recorded ${(state.active.miles||0).toFixed(2)} miles</div>`;$('#finishModal').classList.remove('hidden')};
$('#continueJourneyBtn').onclick=()=>{$('#finishModal').classList.add('hidden');startGps()};
$('#saveJourneyBtn').onclick=()=>{const a=state.active,m=parseFloat($('#finishMilesInput').value);if(!a||!Number.isFinite(m))return alert('Please enter a valid mileage.');const endOdo=parseFloat($('#finishOdoInput').value);state.journeys.push({id:a.id,date:new Date().toISOString(),from:a.from,to:a.to,type:a.type,purpose:a.purpose,miles:m,startOdo:a.startOdo,endOdo:Number.isFinite(endOdo)?endOdo:null,startTime:a.startDate,endTime:new Date().toISOString()});if(Number.isFinite(endOdo))state.settings.currentOdo=endOdo;state.active=null;$('#finishModal').classList.add('hidden');save();showScreen('home')};
$('#resumeBtn').onclick=()=>{showScreen('active');startGps()};

$('#settingsBtn').onclick=()=>{const s=state.settings;$('#driverInput').value=s.driver||'';$('#vanRegInput').value=s.vanReg||'';$('#homeLocationInput').value=s.homeLocation||'';$('#workLocationInput').value=s.workLocation||'';$('#currentOdoInput').value=s.currentOdo??'';$('#monthStartInput').value=s.monthStartOdo??'';$('#monthEndInput').value=s.monthEndOdo??'';$('#settingsModal').classList.remove('hidden')};
$('#closeSettingsBtn').onclick=()=>$('#settingsModal').classList.add('hidden');
$('#saveSettingsBtn').onclick=()=>{state.settings={...state.settings,driver:$('#driverInput').value.trim(),vanReg:$('#vanRegInput').value.trim(),homeLocation:$('#homeLocationInput').value.trim(),workLocation:$('#workLocationInput').value.trim(),currentOdo:parseFloat($('#currentOdoInput').value)||0,monthStartOdo:$('#monthStartInput').value===''?null:parseFloat($('#monthStartInput').value),monthEndOdo:$('#monthEndInput').value===''?null:parseFloat($('#monthEndInput').value)};$('#settingsModal').classList.add('hidden');save()};
$('#resetBtn').onclick=()=>{if(confirm('Reset all test-drive data?')){localStorage.removeItem(STORAGE);location.reload()}};

$('#addMissedBtn').onclick=()=>{$('#missedDate').value=new Date().toISOString().slice(0,10);$('#missedFrom').value=state.settings.workLocation||state.settings.homeLocation||'';$('#missedTo').value='';$('#missedPurpose').value='';$('#missedMiles').value='';$('#missedModal').classList.remove('hidden')};
$$('.missedType').forEach(b=>b.onclick=()=>{missedType=b.dataset.type;$$('.missedType').forEach(x=>x.classList.toggle('selected',x===b))});
$('#closeMissedBtn').onclick=()=>$('#missedModal').classList.add('hidden');
$('#saveMissedBtn').onclick=()=>{const m=parseFloat($('#missedMiles').value);if(!$('#missedFrom').value.trim()||!$('#missedTo').value.trim()||!Number.isFinite(m))return alert('Please complete From, To and Distance.');const d=new Date($('#missedDate').value+'T12:00:00');state.journeys.push({id:String(Date.now()),date:d.toISOString(),from:$('#missedFrom').value.trim(),to:$('#missedTo').value.trim(),type:missedType,purpose:$('#missedPurpose').value.trim(),miles:m,startOdo:null,endOdo:null,startTime:null,endTime:null});$('#missedModal').classList.add('hidden');save()};

$('#previewReturnBtn').onclick=()=>{const t=totals(),rows=companyRows();$('#returnTable').innerHTML=`<tr><th colspan="3">STAGE ELECTRICS VEHICLE MILEAGE RETURN</th></tr><tr><td>Employee</td><td colspan="2">${esc(state.settings.driver||'—')}</td></tr><tr><td>Register No</td><td colspan="2">${esc(state.settings.vanReg||'—')}</td></tr><tr><th>Date</th><th>Details of journey</th><th>Business miles</th></tr>${rows.map(r=>`<tr><td>${new Date(r.date).toLocaleDateString()}</td><td>${esc(r.from)} → ${esc(r.to)}${r.purpose?' · '+esc(r.purpose):''}</td><td>${(+r.miles).toFixed(1)}</td></tr>`).join('')}<tr><td colspan="2"><strong>Total business</strong></td><td><strong>${t.w.toFixed(1)}</strong></td></tr><tr><td colspan="2"><strong>Private miles</strong></td><td><strong>${t.p.toFixed(1)}</strong></td></tr>`;$('#returnModal').classList.remove('hidden')};
$('#closeReturnBtn').onclick=()=>$('#returnModal').classList.add('hidden');
$('#exportCsvBtn').onclick=()=>{const rows=[['Date','From','To','Type','Purpose','Miles','Start Odometer','End Odometer'],...monthJourneys().map(j=>[new Date(j.date).toLocaleDateString(),j.from,j.to,j.type,j.purpose,j.miles,j.startOdo??'',j.endOdo??''])],csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');download(`Mileage_${currentMonthKey()}.csv`,csv,'text/csv')};
$('#exportXlsBtn').onclick=()=>{const t=totals(),rows=companyRows(),html=`<html><head><meta charset="utf-8"></head><body><table border="1"><tr><th colspan="4">STAGE ELECTRICS VEHICLE MILEAGE RETURN</th></tr><tr><td>Month</td><td>${new Date().toLocaleDateString(undefined,{month:'long',year:'numeric'})}</td><td>Employee</td><td>${esc(state.settings.driver)}</td></tr><tr><td>Register No</td><td>${esc(state.settings.vanReg)}</td><td>Start Odo</td><td>${state.settings.monthStartOdo??''}</td></tr><tr><td>End Odo</td><td>${state.settings.monthEndOdo??''}</td><td></td><td></td></tr><tr><th>Date</th><th colspan="2">Details of journey</th><th>Business miles</th></tr>${rows.map(r=>`<tr><td>${new Date(r.date).toLocaleDateString()}</td><td colspan="2">${esc(r.from)} → ${esc(r.to)}${r.purpose?' · '+esc(r.purpose):''}</td><td>${(+r.miles).toFixed(1)}</td></tr>`).join('')}<tr><td colspan="3"><b>Total business</b></td><td><b>${t.w.toFixed(1)}</b></td></tr><tr><td colspan="3"><b>Private miles</b></td><td><b>${t.p.toFixed(1)}</b></td></tr></table></body></html>`;download(`Company_Mileage_Return_${currentMonthKey()}.xls`,html,'application/vnd.ms-excel')};

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('#installBtn').classList.remove('hidden');$('#installHint').classList.remove('hidden');$('#installHint').textContent='Mileage Tracker is ready to install on this device.'});
$('#installBtn').onclick=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('#installBtn').classList.add('hidden');$('#installHint').classList.add('hidden')};
window.addEventListener('appinstalled',()=>{$('#installBtn').classList.add('hidden');$('#installHint').classList.add('hidden')});
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}

renderAll();if(state.active){renderActive();startGps()}
